# Лабораторна робота №2
## Тема: NumPy, pandas i Matplotlib для підготовки, аналізу та візуалізації даних
**Мета:** Ознайомитися з основами роботи з бібліотеками NumPy, Pandas та Matplotlib для аналізу даних, проведення базових операцій з даними та візуалізації результатів.

* **Студент:** Тарас Білуха
* **Група:** МІТ-31
* **Варіант:** 3

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
seed = 3
rng = np.random.default_rng(seed)

x = np.linspace(0, 20, 100)

a = 0.55
b = 4.0
sigma = 1.2

y_hat = a * x + b
noise = rng.normal(loc=0, scale=sigma, size=x.size)
y_observed = y_hat + noise

#Об'єднання у матрицю (100 рядків, 4 стовпці) та вивід характеристик
matrix = np.column_stack((x, y_hat, noise, y_observed))

print("Матриця (перші 5 рядків):\n", matrix[:5])
print("\nХарактеристики матриці:")
print("shape:", matrix.shape)
print("ndim: ", matrix.ndim)
print("size: ", matrix.size)
print("dtype:", matrix.dtype)

Матриця (перші 5 рядків):
 [[ 0.          4.         -0.78214938  3.21785062]
 [ 0.2020202   4.11111111 -0.20966075  3.90145036]
 [ 0.4040404   4.22222222  1.99646879  6.21869101]
 [ 0.60606061  4.33333333  0.7909773   5.12431063]
 [ 0.80808081  4.44444444 -1.96967675  2.47476769]]

Характеристики матриці:
shape: (100, 4)
ndim:  2
size:  400
dtype: float64
